### PR TITLE
Remove application wrapper in A11y section of the guides issue #1515

### PR DESCRIPTION
**Pull request by fozy81**
I've removed the following sections/headings as these seem all related to the application wrapper:

* Configuration (heading)
* Application template wrapper (section)
* Ember applications vs role=''application'' (section)

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @fozy81 . I noticed that your forked repo is many commits behind. To help with Percy snapshots and eliminating merge conflicts, can you rebase your `master` branch?

Normally, if you opened the PR from a branch, I think the commands might be,

```bash
# Get the latest files and branches from upstream
git checkout master
git fetch upstream
git merge upstream/master
git push origin master

# Rebase your branch with your local master branch
git checkout <branch-name>
git pull --rebase origin master
git push -f origin <branch-name>
```

Since you opened the PR from the `master` branch already, you may need to adjust some of the commands above.

Please let us know if you need help!

**Comment by fozy81** [comment]
Thanks for your help @ijlee2 - I think it's fixed now :pray:

**Comment by ijlee2** [comment]
Thanks, @fozy81 . I think your forked repo is now up-to-date, but I don't see any code changes in this PR now?

**Comment by fozy81** [comment]
@ijlee2 thank you - updated...with changes this time :upside_down_face:

**Comment by ijlee2** [comment]
Great, thanks! I think the deletion of `Ember applications vs role="application"` makes sense. I didn't know that we had to manually add ARIA roles when the `<div>` wrapper had been enabled, so it was nice to get to learn that through your PR.

I'll let @MelSumner review this PR and squash-merge it afterwards.

**Review by MelSumner — APPROVED** [review]
Thank you for working on this!

**Comment by fozy81** [comment]
Thanks for helping me with this, good practice getting to grips with git and improving understanding of ARIA.

**Pull request merged**
