### PR TITLE
Update block-content.md

### PR DESCRIPTION
**Pull request by Timbuktu1982**
Incorrect structure and component call corrected...

### CODE REVIEW

**Comment by bertdeblock** [comment]
I don't think anything needed correcting here. The component paths are valid (flat colocation) and the components are just sub components of the message component I assume.

**Comment by Timbuktu1982** [comment]
> I don't think anything needed correcting here? The component paths are valid (flat colocation) and the avatar and username components are just sub components of the message component I assume?

Hello Bert,
yes, if you follow the structure of the previous topics or the example topic, you cannot continue working in the topic at this point.
Follow the structure in the parts before (e.g. here: https://guides.emberjs.com/release/components/conditional-content/)...

**Comment by bertdeblock** [comment]
AFAICT, the guides only make use of flat colocation, I don't see an example that uses nested colocation. Am I overlooking such an example? Also, these docs are not part of the tutorial so I'm not sure what you mean with "you cannot continue working in the topic at this point.". `Message::Avatar` and `Message::Username` or used in later sections as well, so I'm not sure if this is a mistake. But someone from learning can probably confirm.

**Comment by bertdeblock** [comment]
Yeah, I read the previous and next parts, but didn't feel like anything was wrong with those examples. But again, the learning team will confirm. The change in component structure is still wrong I think. All code examples heeft flat colocated file paths.

**Comment by Timbuktu1982** [comment]
https://guides.emberjs.com/release/components/introducing-components/#toc_nesting-components-in-folders

This are not nested and flat colocated file??

**Comment by bertdeblock** [comment]
I can only find one section that refers to nested colocation:

> If you have a component named index.hbs, you can refer to it without the ::Index. So we can refactor app/components/received-message.hbs to app/components/received-message/index.hbs and continue to use it as <ReceivedMessage> without changing all the tags that refer to it:

But all the example file paths that I see use flat colocation (no `index.hbs` filename):

- app/components/received-message/avatar.hbs
- app/components/sent-message/avatar.hbs
- app/components/avatar.hbs
- app/components/received-message/avatar.hbs
- app/components/received-message/username.hbs
- app/components/sent-message/username.hbs
- app/components/my-component.hbs
- app/components/received-message.hbs
- app/components/error-dialog.hbs
- app/components/blog-post.hbs
- app/components/some-component.hbs
- app/components/counter.hbs
- app/components/double-it.hbs

**Comment by bertdeblock** [comment]
Yes, I'm following the confusion about the avatar and username components, but I wasn't talking about that anymore. You are changing from flat colocation to nested colocation here:
https://github.com/ember-learn/guides-source/pull/1847/files#diff-643982adf4ba091b2816a675e207c79ff9a54f289778e48af4e924b9edc1bc95L31-R31.
I don't think this is needed, because alle example file paths in the docs use flat colocation.

**Comment by Timbuktu1982** [comment]
Ah ok. Now i understand you... we discuss about different parts of my PR... sorry for the misstake

**Comment by bertdeblock** [comment]
No worries, happens! 😄

**Pull request closed without merging**
