### PR TITLE
Add example to "handling-events.md"

### PR DESCRIPTION
**Pull request by konstankinollc**
To be crystal clear, I have added an example.

### CODE REVIEW

**Comment by locks** [comment]
Thanks for the contribution @konstankinollc, but isn't this code basically the same as the example right before it?

**Comment by konstankinollc** [comment]
Yes, the code is the same. The point was to show an example of what the paragraph above is saying. For beginners that might be not clear.

**Comment by konstankinollc** [comment]
I realize your concern in the code duplication. I could use #anchors instead to point user onto the code instead. Let me know what do you think.

**Comment by jenweber** [comment]
A link back to the other example would be super!

**Comment by jenweber** [comment]
Hey @konstankinollc, just following up on this PR. Is it something you still want to work on? Let us know if you have any questions! Thanks!

**Comment by jenweber** [comment]
I am closing this PR due to inactivity, however if you would like to get this into the Guides, please feel free to open a new PR. Thanks!

**Pull request closed without merging**
