### PR TITLE
Automatically respond to tutorial PRs

### PR DESCRIPTION
**Pull request by chancancode**

### CODE REVIEW

**Comment by chancancode** [comment]
@rwjblue pointed out to me that this probably wouldn’t work as public PRs would have a readonly token 😔

**Comment by jenweber** [comment]
@chancancode what do you want to be done with this PR? Merge it and see if it works, or close it?

**Comment by chancancode** [comment]
Robert gave me some other ideas to try. This wouldn’t work as-is so I’ll have to keep tweaking it and try the other ideas.

**Comment by chancancode** [comment]
@rwjblue @jenweber this is now ready for review/merge! See https://github.com/ember-learn/guides-source/pull/1288 for what it looks like

**Pull request merged**
