### PR TITLE
Style improvements

### PR DESCRIPTION
**Pull request by chancancode**
This is a spin off from https://github.com/ember-learn/guides-source/pull/1046#issuecomment-529172922, opening for discussion

### CODE REVIEW

**Comment by chancancode** [comment]
The Percy diffs are the “intended” (up for discussion) result of this PR. I can’t approve them but they looked good to me.

**Comment by rwjblue** [comment]
Seems generally good to me, but I'm _definitely_ no designer. Could you include the images for before/after from taht comment in the description here to make it easier to find?

**Comment by chancancode** [comment]
Here are the before/after of some select pages:

Before

After

**Comment by chancancode** [comment]
## Before

Before

* * *

## After

5b5f7eb4316e7aae1a44ef2fbf063b117e02f847301deef8a525b909e24e47cf

**Pull request merged**
