### PR TITLE
fixing all image links (because of new trailing slash issue)

### PR DESCRIPTION
**Pull request by mansona**

### CODE REVIEW

**Comment by jenweber** [comment]
@mansona have you tested this in staging?

**Comment by mansona** [comment]
@jenweber done and done 🎉  

There was a bit of an obscure setting that you needed to change to get the 'trailing-slash' location type to work in dev properly but that's done now and it works. If you want to run it locally just check out the `feature/deploy` branch on the guides-app

Also, I've deployed with this branch in staging so you can see the images are working: http://emberguides.stonecircle.io/v2.17.0/tutorial/acceptance-test/

**Comment by locks** [comment]
https://travis-ci.org/ember-learn/guides-source/builds/331276722#L516 something's going on with CI.

**Comment by mansona** [comment]
CI is not configured for this branch yet, the CI work is on https://github.com/ember-learn/guides-source/pull/15 but I can't fix that PR until this PR is merged 😖 

Circular dependencies 🙄

**Comment by locks** [comment]
#yolo

**Pull request merged**
