### PR TITLE
Grammatical fixes for "Contributing to Ember.js"

### PR DESCRIPTION
**Pull request by jason-maier**
### Contributing

Minor changes for clarity and readability.

### Repositories

Went through all links to make sure they were still accurate.  No changes necessary here.

Part of Octane Guides review https://github.com/ember-learn/guides-source/issues/588

### CODE REVIEW

**Comment by jason-maier** [comment]
Branching issues fixed in separate PR

**Comment by jason-maier** [comment]
Has a grammatical error in their commit message about fixing grammatical errors. :laughing:

**Comment by jenweber** [comment]
Thank you Jason! Did you review all sub-sections or this one page? I'll update the quest issue!

**Comment by jason-maier** [comment]
Hi @jenweber I reviewed all of the subsections under contributing I didn't have any changes for the repositories page!

**Comment by jenweber** [comment]
Fantastic, thanks so much!

**Pull request merged**
