### PR TITLE
Update syntax-conversion-guide.md

### PR DESCRIPTION
**Pull request by MelSumner**
If merged, this PR will remove a sentence that has been reported to be confusing to users (and somewhat contradictory from a technical perspective).

### CODE REVIEW

**Comment by locks** [comment]
Shouldn't we switch the whole thing to use "curly invocation" then?

**Comment by MelSumner** [comment]
@locks @rwjblue Since it's still necessary to use "curly invocation" for some things, we chose the phrase classic invocation (and after many hours of discussion that I genuinely hope we aren't trying to re-litigate).

**Comment by rwjblue** [comment]
> we chose the phrase "classic invocation" to delineate the nuance

Its just not correct, as I mentioned in https://github.com/ember-learn/guides-source/issues/929.

**Comment by MelSumner** [comment]
I'm going to close this PR since the edit now has to happen in a different file.

**Pull request closed without merging**
