### PR TITLE
Further modernize core-concepts.svg

### LINKED ISSUE #1311: further modernize core-concepts.svg
Continue the great work in https://github.com/ember-learn/guides-source/pull/631.

The [core concepts.svg](https://github.com/ember-learn/guides-source/blob/0cdd97b6518d42c7e6b04a4f8d38c7fbbeaa09de/public/images/ember-core-concepts/ember-core-concepts.svg) file has some snippets that need updating:
Screen Shot 2020-02-19 at 15 25 48

- `this.model` should be `@model`
- The route example should use native classes

### PR DESCRIPTION
**Pull request by rajasegar**
Fixes #1311.

image

### CODE REVIEW

**Comment by rwjblue** [comment]
The end of the longer line seems to be getting cut off due to the length of the line with `export default class RentalRoute extends Route {`.

IMHO, we should drop the `export default` bit as this diagram is already not showing _all_ content, and the spirit is still the same:

```js
class RentalRoute extends Route {
  async model() {
    return this.store.findAll('rental');
  }
}
```

**Comment by rajasegar** [comment]
@rwjblue Removed export default

**Comment by rwjblue** [comment]
The updates to the SVG look great thank you @rajasegar! I think this accidentally includes the changes from https://github.com/ember-learn/guides-source/pull/1365 though, mind rebasing those commits out so we can land the SVG fixes?

**Comment by rajasegar** [comment]
@rwjblue Looks like my branch and origin have diverged. I will close this PR and open a new one cherry-picking only the SVG changes

**Pull request closed without merging**
