### PR TITLE
[REFACTOR] Remove depreaction deprecate-router-events

### PR DESCRIPTION
**Pull request by billybonks**
was getting this deprecation while looking into something broccoli related. thought i would offer a fix. here is a reference that you lovely people maintain in some way :) https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events

### CODE REVIEW

**Comment by mansona** [comment]
@locks you tried this before right and it caused an infinite loop in the Ember code right? Was that ever fixed?

**Comment by locks** [comment]
@mansona injecting the `router` service is what causes the loop, this sound be fine!

**Comment by mansona** [comment]
oh... why aren't we suggesting this in the deprecation guide then? 🤔

**Comment by locks** [comment]
@mansona OPs link is suggesting exactly this? I'm conffussee

**Comment by billybonks** [comment]
I guess the question is under what conditions does injecting the router cause an infinite loop. Because from what I know that shout be okay.

**Comment by locks** [comment]
@billybonks if you inject the router service into `EmberRouter`, because they depend on each other :x

**Pull request merged**
