### PR TITLE
refactor links inline

### LINKED ISSUE #330: Markdown link inconsistencies
Since working on the linting and spellchecking improvements, I've noticed that the guides are inconsistent on how markdown links are created.

In the cli-guides, there are all inline `[link name](https://somelink...)` and the guides-source has a mix between inline and keyed links.  In some cases within the same file.  Not sure about other docs.

Key links are in the markdown and the links defined at the bottom of the file

```
[My Link][]

[My Link]: http://www.myspeciallink.com
```

This came about from having different contributors working on the guides.  I raise the question should the format be standardized and the guides refactored to match?

While I normally use inline links in my markdown, the use of keys in large document sets has advantages.

- They improve markdown readability, which makes reviewing PRs easier because the text isn't interrupted by URLs
- If you use the same link multiple times in a document, you only have to define it in one location
- Improves maintainability. If a link needs to be updated, there is only one place to look.  Each document needs to be to visited, but you don't have to search through the document

There are probably more benefits  that I'm missing. The Remark linters will flag keys without a definition, so editing errors will be caught. Dead links are still an issue but I believe @mansona is working a solution for that.

### PR DESCRIPTION
**Pull request by maxwondercorn**
* Refactor links to inline, v3.x to release
* Updated CONTRIBUTING.md

PR refactors against current master

Resolves #330

### CODE REVIEW

**Comment by locks** [comment]
Master is the source of truth :)

**Comment by MelSumner** [comment]
Thank you for doing this work! It looks like some updates will need to happen before we can merge, to resolve some conflicts. Once that is finished, I'm happy to merge this PR! :+1:

**Comment by maxwondercorn** [comment]
@MelSumner conflicts fixed

**Comment by locks** [comment]
Double checked!

**Comment by maxwondercorn** [comment]
I see there are some non-inline links in 3.9 and 3.10. I will do another PR to fix those

**Comment by locks** [comment]
Thanks for the help!

**Pull request merged**
