### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Timbuktu1982**
remove "Message" because not needed (see example picture)

### CODE REVIEW

**Review by MelSumner — CHANGES_REQUESTED** [review]
The label is required and should not be removed. While an accessible name for the input is required for users with assistive technology (see https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html), all users benefit from having a clear label letting them know what information the input field requires.

**Comment by MinThaMie** [comment]
@MelSumner Should we update the image? Because that does not show the label.
Screenshot 2023-02-07 at 14 39 23

**Comment by MelSumner** [comment]
@MinThaMie yes, definitely.

**Comment by MinThaMie** [comment]
I've created a new issue #1898 that you or I could pick up, but to make sure we're not merging this I'll close this PR.

**Pull request closed without merging**
