### PR TITLE
updated "ember server" references to "ember serve"

### PR DESCRIPTION
**Pull request by StreakInTheSky**
Was going through the tutorial and noticed they were telling us to use the "ember server" command to run the dev server. This was inconsistent with the quickstart and what's documented in the CLI, so I updated it.

Also noticed the CLI says to run "npm start", which is an alias to "ember serve", but just wondering if that should be updated as well.

Thanks!

### CODE REVIEW

**Review by bertdeblock — APPROVED** [review]

**Review by MinThaMie — CHANGES_REQUESTED** [review]
This file is generated from https://github.com/ember-learn/super-rentals-tutorial/blob/723f119fe77897630639c14d0fdd79a089a9043b/src/markdown/tutorial/part-1/01-orientation.md so you can change it there if you want. If not I could change it for you!

Thanks for catching this!

**Comment by StreakInTheSky** [comment]
woops! did not notice that comment about it being generated! I'll change it at the other repo. Thanks!

**Comment by StreakInTheSky** [comment]
Had a question about the edits. But basically did a search and replace, and wanted to confirm a few changes. Made a new issue in the other repo since that seems liked a more appropriate place to continue the conversation. https://github.com/ember-learn/super-rentals-tutorial/issues/212

Thanks!

**Comment by MinThaMie** [comment]
Since [this](https://github.com/ember-learn/super-rentals-tutorial/pull/213) was merged, let's close this one :)

**Pull request closed without merging**
