### PR TITLE
Fix redirects

### PR DESCRIPTION
**Pull request by mansona**
This is intended to fix an issue that was reported that https://guides.emberjs.com/release/reference/syntax-conversion-guide/ doesn't work any more. 

We should verify on the Netlify Preview that the path redirects to the right place 👍

### CODE REVIEW

**Comment by locks** [comment]
I approved but [https://deploy-preview-987--ember-guides.netlify.com/reference/syntax-conversion-guide](https://deploy-preview-987--ember-guides.netlify.com/reference/syntax-conversion-guide) doesn't actually seem to work, along with [https://deploy-preview-987--ember-guides.netlify.com/reference/syntax-conversion-guide](https://deploy-preview-987--ember-guides.netlify.com/reference/syntax-conversion-guide).

**Comment by mansona** [comment]
@locks that's because the url is actually deploy-preview-987--ember-guides.netlify.com/release/reference/syntax-conversion-guide 😂 you were missing the `release` part

**Comment by locks** [comment]
Ah, it's because https://guides.emberjs.com/release/reference/syntax-conversion-guide/ redirects to https://guides.emberjs.com/reference and I copied that one instead.

**Comment by mansona** [comment]
I had a chat with @locks just to clarify that he's ok to merge, and he is 🎉 🎉

**Pull request merged**
