### PR TITLE
update ember inspector screenshots for tackling deprecations (#314)

### LINKED ISSUE #314: Update "Ember Inspector - Tackling Deprecations"
Currently, this guide shows how to trace the source of a deprecation and it points to `my-app/views/posts.js:8`. It has been a while since we have actually had Views in the framework, so we should update the page to something more contemporary.

### PR DESCRIPTION
**Pull request by dbendaou**
This PR update `ember-inspector/tackling-deprecations` pictures 

I don't understand why the deploy is falling.. This is my first PR btw so some help would be appreciate 🤓

Closes #314

### CODE REVIEW

**Comment by dbendaou** [comment]
capture d ecran 2019-01-29 a 23 06 40



capture d ecran 2019-01-29 a 23 06 49

**Comment by locks** [comment]
Thanks for the help @dbendaou. The deploy is currenty failing because we are in the middle of restructuring the repository (see https://github.com/ember-learn/guides-source/pull/365), so it's definitely not your fault!

**Comment by dbendaou** [comment]
Cool thanks 👍

**Comment by locks** [comment]
Congrats on your first guides-source PR 😁 Keep'em coming!
Drop by our Discord (link at https://emberjs.com/community/) if you want to discuss anything with the learning team or join in our weekly Thursday team call.

**Comment by dbendaou** [comment]
Would be a pleasure 🤗

**Pull request merged**
