### PR TITLE
fix: further modernize core-concepts.svg

### PR DESCRIPTION
**Pull request by rajasegar**
Fixes #1366

### CODE REVIEW

**Comment by rajasegar** [comment]
@rwjblue This is the new PR with only SVG file changes.

**Comment by rwjblue** [comment]
I don't fully grok the CI failure here:

```
$ [ "$TRAVIS_PULL_REQUEST_SLUG" != "ember-learn/guides-source" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "master" ] && export PERCY_BRANCH="fork-${TRAVIS_BUILD_NUMBER}"
The command "[ "$TRAVIS_PULL_REQUEST_SLUG" != "ember-learn/guides-source" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "master" ] && export PERCY_BRANCH="fork-${TRAVIS_BUILD_NUMBER}"" exited with 1.
```

All of the actual tests seem to have passed 🤔

**Comment by amyrlam** [comment]
@rajasegar @rwjblue This change looks good. I believe that https://github.com/ember-learn/guides-source/pull/1395 fixed the unrelated Percy error. Can you please rebase with master?

**Comment by rajasegar** [comment]
@amyrlam Rebased

**Comment by rajasegar** [comment]
Thanks @amyrlam

**Pull request merged**
