### PR TITLE
Create .nvmrc

### PR DESCRIPTION
**Pull request by mansona**
Using the latest node version to see if it will improve build times on netlify. This should **not** be merged if it does nothing 😄

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
This didn't seem to help🤕. Thanks for trying though 🙂

**Comment by sivakumar-kailasam** [comment]
https://github.com/ef4/prember/issues/9 is probably worth revisiting to see if it helps.

**Comment by mansona** [comment]
I was trying to look into something else before my break, the issue with rendering multiple pages at once is that it won't do much for a speed up on a single CPU machine (or VM) 🤔 Essentially I'm assuming that we're CPU bound with this process

Do we have an issue that we can use to track performance?

**Comment by sivakumar-kailasam** [comment]
Travis VMs seem to have two cores. We closed the original issue since since it's resolved.

**Pull request closed without merging**
