### PR TITLE
Refactor links to inline

### LINKED ISSUE #330: Markdown link inconsistencies
Since working on the linting and spellchecking improvements, I've noticed that the guides are inconsistent on how markdown links are created.

In the cli-guides, there are all inline `[link name](https://somelink...)` and the guides-source has a mix between inline and keyed links.  In some cases within the same file.  Not sure about other docs.

Key links are in the markdown and the links defined at the bottom of the file

```
[My Link][]

[My Link]: http://www.myspeciallink.com
```

This came about from having different contributors working on the guides.  I raise the question should the format be standardized and the guides refactored to match?

While I normally use inline links in my markdown, the use of keys in large document sets has advantages.

- They improve markdown readability, which makes reviewing PRs easier because the text isn't interrupted by URLs
- If you use the same link multiple times in a document, you only have to define it in one location
- Improves maintainability. If a link needs to be updated, there is only one place to look.  Each document needs to be to visited, but you don't have to search through the document

There are probably more benefits  that I'm missing. The Remark linters will flag keys without a definition, so editing errors will be caught. Dead links are still an issue but I believe @mansona is working a solution for that.

### PR DESCRIPTION
**Pull request by maxwondercorn**
Refactored markdown links to inline for consistency and match learning team requirements.  Links from 3.0.0 on have been converted to inline.

As I started this several weeks ago, I will probably do another PR to clean up links added after I started the refactoring

resolves #330

### CODE REVIEW

**Comment by locks** [comment]
Can you rebase? 🙈

**Comment by maxwondercorn** [comment]
working on it

**Comment by maxwondercorn** [comment]
@locks It looks like I remerged the branch again when trying to rebase.  I've only rebased a few times but this one was different then what I've seen in the past.  I don't know if this can all be squashed into one commit or I need to do something on my end?  We also could close the PR and I can generate a new one based on updated master.

**Comment by jessica-jordan** [comment]
@maxwondercorn Do you mind rebasing your branch onto master or send another PR with your commits based on the current master to the repo? Happy to review as well!

**Comment by maxwondercorn** [comment]
I'll just do another PR easier all the way around. Hopefully, I can do it later today

**Pull request closed without merging**
