### PR TITLE
update triple curly brackets guidance issue #1421

### PR DESCRIPTION
**Pull request by fozy81**
Cleaned up PR. for issue #1421

### CODE REVIEW

**Comment by ijlee2** [comment]
@fozy81 Thank you, too, for your patience with getting the commit history right.

I think what you wrote is a great start. What do you think about the following change? (For testing, I wrote each paragraph in one line. Feel free to break the line into a few according to the guidelines for this repo.)

```handlebars
<div class="cta-note-message">
  <p>
    Triple curly brackets are a convenient way to put dynamic HTML into Ember templates, but are not recommended for production apps. Inserting unknown HTML can create unexpected results and security issues. Be sure to sanitize the HTML before you render it.
  </p>
  <p>
    We can use the <a href="https://api.emberjs.com/ember/release/functions/@ember%2Ftemplate/htmlSafe">htmlSafe</a> function to mark a sanitized HTML as safe, then use double curly brackets to render the HTML. We can also create a <a href="../helper-functions">helper</a> that sanitizes the HTML, marks it as safe, and returns the output.
  </p>
</div>
```

After making an appropriate change (feel free to incorporate my suggestion at its entirety, or adjust further as needed), will you apply the changes to `v3.15` to `v3.20`?

**Comment by fozy81** [comment]
@ijlee2 Thanks for your feeback, I've update the wording and added line breaks as per contributing guidance. If this all looks good, I'll backport to previous versions (v3.15 to v3.20).

**Comment by ijlee2** [comment]
@fozy81 Looks good! I look forward to see the backports.

**Comment by fozy81** [comment]
@ijlee2 Backports are done. Please review.

**Comment by ijlee2** [comment]
@fozy81 Can you make 1 additional change? The API Guides _are_ versioned so we do want to provide the version number in the Ember Guides:

```
# For v3.15.0:
https://api.emberjs.com/ember/3.15/functions/@ember%2Ftemplate/htmlSafe
```

(Confusing, right?)

**Comment by fozy81** [comment]
@ijlee2 Thanks for catching that. I updated the API link.

**Review by ijlee2 — APPROVED** [review]
Thanks very much for all of your work!

**Pull request merged**
