### PR TITLE
Use page-title helper from ember-page-title addon

### PR DESCRIPTION
**Pull request by afzal273**
https://github.com/ember-learn/guides-source/issues/1608

### CODE REVIEW

**Review by jaredgalanis — CHANGES_REQUESTED** [review]
@afzal273 looks good, but there is a failing test. Can you take a look?
Screen Shot 2021-03-29 at 2 34 17 PM

**Comment by afzal273** [comment]
Let me fix the issue, thanks for the note!

**Review by jaredgalanis — APPROVED** [review]
Thank you for your work on this! 👍  🎉

**Comment by afzal273** [comment]
> Thank you for your work on this! 👍 🎉

Thanks Jared!

**Pull request merged**
