### PR TITLE
Issue 1421

### PR DESCRIPTION
**Pull request by fozy81**
Update 'Zoey says' triple curly usage guidance

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @fozy81. I noticed that your pull request contains commits by other contributors. I want to be cautious with merging your PR, so will you try these commands to correct your branch?

```bash
# 1a. Check out your local branch
git checkout issue-1421

# 1b. Undo the 9 commits made in the pull request (we'll restore the actual commit later, no worries)
git reset --hard HEAD~9


# 2a. Set upstream
git remote set upstream git@github.com:ember-learn/guides-source.git

# 2b. Check that setting upstream worked (you will see 2 lines for origin, and another 2 lines for upstream)
git remote -v


# 3a. Get the latest code and branches
git checkout master
git fetch upstream
git merge upstream/master

# 3b. Push the latest code to your forked repo (optional)
git push origin master


# 4a. Rebase your branch
git checkout issue-1421
git pull --rebase origin master

# 4b. Restore your commit
git cherry-pick db9d7c6

# 4c. Push the commit to your repo
git push -f origin issue-1421
```

If these commands were successful, we'll see only 1 commit made in this pull request.

**Comment by ijlee2** [comment]
To keep your forked copy up-to-date, you can run the commands in steps 3a and 3b every now and then.

**Comment by fozy81** [comment]
@ijlee2 thanks, hope that's better. Still getting the hang of upstream remotes etc.

**Comment by ijlee2** [comment]
@fozy81 No problem. Yeah, `git` can be confusing. It's hard for me to visualize the commits, heh.

I'm still seeing 6 extra commits in this pull request. I think the reason is that your local `master` branch is a bit out of sync. https://github.com/fozy81/guides-source/tree/master shows that the branch is 6 commits ahead and 27 commits behind. Ideally, we would only see 27 commits behind.

Let's try these commands now:

```bash
# 0a. Correct the default branch
git checkout master
git reset --hard HEAD~6

# 0b. Get the latest code and branches
git fetch upstream
git merge upstream/master

# 0c. Push the latest code to your forked repo (you should see in GitHub that your branch is now "even")
git push -f origin master


# 1a. Check out your local branch
git checkout issue-1421

# 1b. Undo the 7 commits made in the pull request (we'll restore the actual commit later, no worries)
git reset --hard HEAD~7


# 2a. Rebase your branch
git pull --rebase origin master

# 2b. Restore your commit
git cherry-pick 5e011ac

# 2c. Push the commit to your repo
git push -f origin issue-1421
```

If steps 1 and 2 didn't work, I'd just create a new branch and open a new pull request. 😄

**Comment by fozy81** [comment]
Thanks for your patience @ijlee2 , I think a little better now?

**Comment by fozy81** [comment]
I am sorry @ijlee2 I've now managed to merge changes for a different issue on this branch.. I'll try again tomorrow.

**Comment by fozy81** [comment]
Cleaned up PR moved on to new branch here: https://github.com/ember-learn/guides-source/pull/1563

**Pull request closed without merging**
