### PR TITLE
Octane Tutorial Updates

### PR DESCRIPTION
**Pull request by adrian5**
I guessed the intended structure of the last sentence regarding the JSON:API. If it's different, then please edit my PR accordingly.

### CODE REVIEW

**Comment by chancancode** [comment]
Thanks @adrian5, the changes look good to me. However, these files are not the source of truth. The source is located at a different repo – at the top of the file you edited, there is a comment pointing you to its source. Do you mind reopening the pull request in the source repo?

**Comment by adrian5** [comment]
Hello Godfrey, I'm not seeing the comment you mentioned. Could you post a direct link to the correct repo? I got this repo from a user in the Discord channel after failing to find any source myself (I looked in the `master` branch and hadn't considered the `octane` one).

**Comment by chancancode** [comment]
@adrian5 I think you may be looking at the master branch. If you expand the diff in your PR all the way up, you should see this:

> Heads up! This is a generated file, do not edit directly. You can find the source at https://github.com/ember-learn/super-rentals-tutorial/blob/master/src/chapters/08-working-with-data.md

**Comment by chancancode** [comment]
Closing in favor of https://github.com/ember-learn/super-rentals-tutorial/pull/91. Thanks again!

**Pull request closed without merging**
