### PR TITLE
Issue 393 - TOC rearranging

### PR DESCRIPTION
**Pull request by MelSumner**
If merged into the octane branch, this PR resolves issue #393 by re-ordering the table of contents (as outlined in RFC 431).

### CODE REVIEW

**Comment by jenweber** [comment]
Should this PR review & merge wait until we have pages for some of those topics? Anatomy of an app doesn't exist, for example.

**Comment by MelSumner** [comment]
@jenweber we were thinking that we would add in the sections in the octane branch, even if the page has no content. We want to be able to see the content gaps easily.

**Comment by jenweber** [comment]
@MelSumner can I get your help with the merge conflicts?

I am not confident about removing tutorials, since it necessitates infra work that I don't think we have time for before the preview. The others make sense to me. Can you share more about why you think tutorials should be removed at this stage? Thanks!

**Comment by jenweber** [comment]
locks explained that tutorials infra is mostly done already. Merged! 🎉 Thanks for your help!

**Pull request merged**
