### PR TITLE
WIP Octane: Update prose in tutorial

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by locks** [comment]
Heya, why are you adding it back in?

**Comment by NullVoxPopuli** [comment]
I really have no idea what I'm doing, and I didn't know where else the tutorial was. haha

**Comment by locks** [comment]
I'm hoping to have https://github.com/ember-learn/tutorials ready2go before Octane.
Someone is doing an Octane revamp of super-rentals that you might want to coordinate with: https://github.com/ember-learn/super-rentals/pull/123!

**Comment by jenweber** [comment]
@locks I asked @NullVoxPopuli to add it back in since we need to start work on it, and it makes sense to do it here until the migration ships.

**Comment by muziejus** [comment]
Is this where I can stand in and officially throw my had in the ring for the copy editing?

**Comment by jenweber** [comment]
Superceded by #1002

**Pull request closed without merging**
