### PR TITLE
Added links to CLI Guides in Getting Started

### LINKED ISSUE #1560: Add link to CLI Guides in Getting Started
## Description

In the `Getting Started - How to Use the Guides` section, the link for `Ember CLI` points to `Configuration - Configuring Ember CLI` section. The latter (configuring your app ) is an advanced topic and doesn't show much information.

Please link to the CLI Guides (https://cli.emberjs.com/release/) instead.

## TODOs

- [ ] Update the Markdown file `guides/release/getting-started/index.js`:

    ```markdown
    <!-- Before -->
    * [Ember CLI](../configuring-ember/configuring-ember-cli/) - A robust development toolkit to create, develop, and build Ember applications. When you see a command `$ ember <command>` instruction throughout the guides, that's Ember CLI!

    <!-- After -->
    * [Ember CLI](https://cli.emberjs.com/release/) - A robust development toolkit to create, develop, and build Ember applications. Learn [basic commands](https://cli.emberjs.com/release/basic-use/cli-commands/) from the CLI Guides.
    ```

- [ ] Make the same changes to previous versions of Ember, starting with `v3.15.0`:

    - `guides/v3.15.0/getting-started/index.js`
    - `guides/v3.16.0/getting-started/index.js`
    - `guides/v3.17.0/getting-started/index.js`
    - `guides/v3.18.0/getting-started/index.js`
    - `guides/v3.19.0/getting-started/index.js`
    - `guides/v3.20.0/getting-started/index.js`
    - `guides/v3.21.0/getting-started/index.js` (assuming the Ember Guides shows `v3.22` for `release`)

## Screenshots

Getting Started - How to Use the Guides:

getting-started

Configuration - Configuring Ember CLI:

configuring-ember-cli

### PR DESCRIPTION
**Pull request by hbutau**
This issue closes #1560.

### CODE REVIEW

**Review by ijlee2 — CHANGES_REQUESTED** [review]
The changes for `release` directory look good.

The CLI Guides, unlike Ember Guides, isn't versioned at the moment. So all links to `cli.emberjs.com` will need to point to `release` version. Can you update the links in `v3.15.0`-`v3.20.0`?

**Comment by hbutau** [comment]
> The changes for `release` directory look good.
> 
> The CLI Guides, unlike Ember Guides, isn't versioned at the moment. So all links to `cli.emberjs.com` will need to point to `release` version. Can you update the links in `v3.15.0`-`v3.20.0`?

Sure let me do so.

**Comment by hbutau** [comment]
Done.

**Review by ijlee2 — APPROVED** [review]
Thanks for helping out with the Ember Guides again! 🌟

**Pull request merged**
