### PR TITLE
WIP Remove/Redirect quickstart section to tutorials.emberjs.com

### LINKED ISSUE #444: Update Octane guides section - Getting Started: Quick Start
Your PR should target the `octane` branch.

## Goal
Update the "Quick Start" sub-section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Remove file and reference from table of contents
- [ ] Set up redirect to tutorials.emberjs.com

### PR DESCRIPTION
**Pull request by wordofchristian**
closes #444

Tested on with this netlify preview https://deploy-preview-666--ember-guides.netlify.com/release/getting-started/quick-start/

Also an open question: Do we want to redirect any other versions of the quickstart to the new tutorial or just the release version?

### CODE REVIEW

**Comment by wordofchristian** [comment]
Temporarily changing the base to master to trigger a netlify build for testing

**Comment by wordofchristian** [comment]
Manual testing done

**Comment by jenweber** [comment]
@locks I need your help to figure out how/when/if we can get this in sooner. Basically I don't want to redirect until whatever we are redirecting _to_ has Octane content. Thoughts?

**Comment by wordofchristian** [comment]
I think @locks mentioned IRL that he was in the process for rewriting that section in the new repo, but that if someone else wanted to take it on that wouldn't be a lot of wasted effort because it's so short.

**Comment by locks** [comment]
Thanks for your help @wordofchristian! We are still figuring out some things about the architecture of the tutorials, so we will need to revisit this later in the future. Once again thank you for your time!

**Pull request closed without merging**
