### PR TITLE
Update for readability

### PR DESCRIPTION
**Pull request by lenoraporter**
This PR may be very opinionated or personal preference, but I thought the wording of this sentence is a bit awkward.

> Let's update our helper to look if a property exists in an array of communityPropertyTypes, if so, we'll return either 'Community' or 'Standalone':

I thought maybe `see` would sound a little better. Maybe the entire sentence needs to be restructured. `Look` just doesn't seem like the appropriate word here.

> Let's update our helper to see if a property exists in an array of communityPropertyTypes, if so, we'll return either 'Community' or 'Standalone':

This particular wording exist in 3.11, 3.12, 3.13, and 3.14.

This is not a hill I'm interested in dying on but I thought I should give it a shot. If you don't think this is appropriate, I'm okay with that.

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @lenoraporter. Thanks for going over the tutorial and suggesting a change.

I don't have context to why you thought a change to the passage would be good. For posterity, in the PR description, can you explain the motivation for change?

I also noticed that the change was for Ember 3.11. I haven't checked what would happen to 3.12 - release; you may want to describe in the description whether targeting 3.11 only was intended.

Let me copy @chancancode, who can guide you through making a PR for the tutorial.

**Comment by lenoraporter** [comment]
Hey @ijlee2! Thank you for the reply!

Just for context, I've been streaming on Twitch each morning learning Ember 3.11 (This is the version my company uses). I had a few meetings so I didn't finish updating this PR but I will finish updating it now so thanks for the reminder!

As I read this line, it didn't really read well in my opinion. Maybe `see` isn't the right change either but I thought `look` made the sentence sound a little awkward. I'm also okay if you all think this change shouldn't happen.

It seems this wording is used until 3.14.

Also, I can't wait to know what I need to change and if this change is even worth it. Thank you and thanks in advance @chancancode.

**Comment by chancancode** [comment]
@ijlee2 @lenoraporter The new tutorial is available on 3.15 and above, since this is talking about the old one I don't have anything useful to add here. However, generally speaking, if we are making a change to 3.11, I think it does make sense to do the same for 3.11 - 3.14 (especially when the change is small), so that it makes back-porting future changes more straightforward.

**Comment by ijlee2** [comment]
@lenoraporter Thanks for the explanation. Really like the idea of streaming learning Ember on Twitch!

I agree that `see` sounds better than `look` in the context of the sentence. Will you also make the change to 3.12-3.14?

**Comment by lenoraporter** [comment]
Let's do this! Sorry for the delay. Some things came up for me but I'll get right to this today.

**Comment by ijlee2** [comment]
Awesome! No worries about the delay.

**Comment by lenoraporter** [comment]
Whew! There were a lot of files to rebase! This did not turn out the way I thought so I may need help with this one!

**Comment by ijlee2** [comment]
Haha, it's no problem. Yeah, I find working with git commands to be tricky, because visualizing what would happen to the commit history isn't easy.

Can I suggest closing this PR and opening a new one? First, let's make sure that [your forked repo](https://github.com/lenoraporter/guides-source/tree/master) (currently 1192 commits behind) has the latest files from this repo.

Below, I described 7 steps for getting the latest files (two are optional). If you run into a problem with a step, feel free to ask questions in this PR. I will leave this PR open until you can make a new one.


## Step-by-step guide

1\. I will use my forked repo as a visual reference.

We see that it's currently 4 commits behind. The goal is to make this number 0 (the branch will be "even").

step 1
<br>


2\. (optional) Let's double-check that the "upstream" points to this repo. We can type `git remote -v` to check.

The "origin" tells us where changes would occur when we run `git push origin <branch_name>`. (Hopefully, to the forked repo.)

step 2
<br>


3\. Next, let's run `git fetch upstream` to get the latest branches from `upstream`.

This command may be useful if you need to branch from a branch other than `master` (the default branch). (It looks like Godfrey has worked on updating the Super Rentals tutorial!)

step 3
<br>


4\. After fetch, we can run `git merge upstream/master` to get the latest code in `master` from `upstream`.

Since your local `master` branch is 1192 commits behind, the terminal output will likely show many more file changes. Nothing to be alarmed.

step 4
<br>


5\. (optional) Let's check if merge was a success by typing `git log`. We can compare the top log message to that in the [original repo's commit history](https://github.com/ember-learn/guides-source/commits/master).

At the time of writing, the most recent commit is related to updating `lodash`. ✅

step 5
<br>


6\. The merge updates the code on your local machine. We want the forked repo (the "origin") to have the updated code too!

Let's run `git push origin master` to push the update back to the forked repo.

step 6

If we refresh the forked repo website, we will see that the branch is now "even." 🎉

step 6b
<br>


7\. Now, you can create a branch, commit changes, and push the commit to `origin`, just like you had done before.

step 7

As a reminder, after you create a branch, you can type `git log` to check that you're starting from the right place in the commit history.

step 7b

**Comment by lenoraporter** [comment]
This is perfect! I need to keep this message forever! Thank you! I'll create a new branch and make the changes now. Thanks a ton!

**Comment by lenoraporter** [comment]
Screen Shot 2020-07-19 at 7 26 47 PM

All even! Making a new branch now.

**Comment by ijlee2** [comment]
Nice! I'm glad to hear the steps worked.

**Comment by ijlee2** [comment]
Closing this PR in favor of #1486.

**Pull request closed without merging**
