### PR TITLE
Referencing this.model makes the guide work

### PR DESCRIPTION
**Pull request by bf4**
## Problem

No scientists showed up in the list of scientists till I changed `@model` to `this.model`.  It stopped me from following the guide really early on.

I don't know what to expect.

## Dev Environment

I'm on 

- node 10.15.1
- npm 6.9.0
- osx sierra

following
https://octane-guides-preview.emberjs.com/release/getting-started/quick-start/

meaning I installed

- ember 3.13.0-beta.1

and ran `ember new ember-quickstart -b @ember/octane-app-blueprint`

package.json

```json
{
  "name": "ember-quickstart",
  "version": "0.0.0",
  "private": true,
  "description": "Small description for ember-quickstart goes here",
  "repository": "",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "@ember/optional-features": "^0.7.0",
    "@glimmer/component": "^0.14.0-alpha.12",
    "babel-eslint": "^10.0.2",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.2.20",
    "ember-cli": "3.13.0-beta.1",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.8.0",
    "ember-cli-dependency-checker": "^3.1.0",
    "ember-cli-htmlbars": "github:ember-cli/ember-cli-htmlbars#791bde491de84987e1b1f6c24931ca6a13a0632b",
    "ember-cli-htmlbars-inline-precompile": "^2.1.0",
    "ember-cli-inject-live-reload": "^2.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-uglify": "^3.0.0",
    "ember-data": "^3.11.4",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^2.0.0",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.4.1",
    "ember-resolver": "^5.1.3",
    "ember-source": "3.13.0-beta.5",
    "ember-template-lint": "^1.5.0",
    "ember-welcome-page": "^4.0.0",
    "eslint": "^6.1.0",
    "eslint-plugin-ember": "^6.2.0",
    "eslint-plugin-node": "^9.0.1",
    "loader.js": "^4.7.0",
    "qunit-dom": "^0.9.0"
  },
  "engines": {
    "node": "8.* || >= 10.*"
  }
}
```

package-lock.json

[package-lock.json.txt](https://github.com/ember-learn/guides-source/files/3614503/package-lock.json.txt)

### CODE REVIEW

**Comment by bf4** [comment]
related https://github.com/ember-learn/guides-source/issues/633

**Comment by bf4** [comment]
@NullVoxPopuli see you tomorrow

**Comment by bf4** [comment]
seems like part of the issue is

https://blog.emberjs.com/2019/09/13/the-ember-times-issue-115.html

> Starting with Ember Octane (3.14), you can use a named argument, @model, in the route template to refer to your data from the model() hook. The Ember Octane Guides have been updated to show uses of @model.

but that's not available in `npm install -g ember` which has installed `3.13.0-beta.1` on my machine.  

maybe there's some 'serve' command that loads an octane build?

**Comment by bf4** [comment]
tagging @rwjblue as I see you maintain the blueprint. (hi :)

**Comment by bf4** [comment]
oh, ref https://github.com/ember-learn/guides-source/pull/1044

**Comment by chancancode** [comment]
Yep. This requires canary today, but beta should work once the release happens this week. In retrospect I think we switched the octane blueprints to track beta a little to eagerly, but given the timeframe, I think it’s probably not worth reverting the guides or the blueprint.

**Comment by chancancode** [comment]
See also https://github.com/ember-learn/guides-source/issues/1065

**Comment by bf4** [comment]
@chancancode Thanks for looking at this.  Maybe the assumption is that someone going through the octane guide already knows ember enough not to get stuck on this?  Or do you think the guide to be include installing an ember version known to work with it?

**Comment by jenweber** [comment]
Hi @bf4, by the time the preview/WIP guides are shown on guides.emberjs.com, developers need to make sure they are on the latest version of Ember. In the meantime, we base our work off canary. 

I am closing this PR because we need to show `@model` at the time these guides become official. However if you would like to make  a new PR that adds a note to the quickstart indicating that someone should have installed the latest version of the CLI to follow along, that would be good! Otherwise they may not realize that's important.

Thanks for trying out Octane! Let us know if you spot anything else that seems wrong after you are running on canary.

**Comment by bf4** [comment]
I ran `npm install --save-dev https://s3.amazonaws.com/builds.emberjs.com/canary/shas/9ae862a842b8c6522ef9f8c13822bec109716513.tgz` to install the canary release and it worked.  But I think the blueprint was supposed to install this, no?

**Comment by chancancode** [comment]
Yeah. It was doing that until around last week where it switched to track
beta releases. We are working on releasing canary into beta today or
tomorrow.

**Pull request closed without merging**
