### PR TITLE
Add A11y Mascots to Accessibility Index

### PR DESCRIPTION
**Pull request by hergaiety**
Continuing the effort (#1463, #1466, #1467) of adding visuals to the Ember Guides for visual interest of developers, breaking up walls of text and generally enhancing the guides visual appearance. This PR adds the Ember A11y versions of the [Zoey and Tomster mascots](https://emberjs.com/mascots/) in a stylized way to the intro page of the Accessibility section.

## Preview

Screen Shot 2020-07-10 at 10 31 47 PM

### CODE REVIEW

**Comment by ijlee2** [comment]
Hi, @hergaiety. It looks like you combined two Ember mascots to create the image. I wanted to confirm if we need approval from Leah Silber to modify the mascots (maybe you already did?). https://emberjs.com/mascots/faq

**Comment by ijlee2** [comment]
@wifelette Hello! 👋 When you get a chance, would you mind reviewing this PR so that we may have your approval for use of mascots?

**Comment by wifelette** [comment]
Hi! Sorry for the delay. @hergaiety Can you confirm that the only modification is the placement + blurring of the Tomster? If so, A+, and it looks good. If it's more, please list the modifications so I can review them with Lindsey :)

**Comment by hergaiety** [comment]
@wifelette I technically also hid the rights reserved symbol over Tomster's right hand as it was blurred. There's still a rights reserved symbol over Zoey's left hand, and it's all one image tightly grouped together so I don't believe this is an issue.

No other visual changes were made.

**Comment by ijlee2** [comment]
@hergaiety I'll go ahead and merge this PR. Can you make a follow-up PR so introduce the picture to `/guides/v3.19.0`?

**Pull request merged**
