### PR TITLE
Update release guide with ember-inspector v4.3.4 screenshots

### LINKED ISSUE #1406: Update screenshots for Ember Inspector section
**NOTICE** https://github.com/emberjs/ember-inspector is releasing v4.0.0 soon, so any that should be the baseline for this work, and not the currently published version (v3.13.2 on my Firefox browser).

At the moment, some of the screenshots in the Ember Inspector chapter of the guides are out of date. For example, the screenshots at https://guides.emberjs.com/v3.17.0/ember-inspector/component-tree/ still show the "View Tree" panel, which I believe has been removed for some time now. And, of course, https://guides.emberjs.com/v3.17.0/ember-inspector/view-tree/ should be removed.

The first phase of the work is to identify which screenshots are out of date so they can be replicated. For now I would not change the introduction page. Part of this work is also confirm which versions of ember.js make Ember Inspector show the "View Tree" or not, so we can backport the updated screenshots to the Guides for that version.

Once we have agreed on the work identified in the previous phase, we move to the second phase where we create issues to address said work.

### PR DESCRIPTION
**Pull request by neojp**
This PR includes:

- [x] Update screenshots to match the latest version of Ember Inspector (currently `v4.3.4`)
- [x] Remove Tree View
- [x] Remove Tree View page references
- [x] Update guide's content to match screenshots

Closes #1406

### CODE REVIEW

**Comment by ijlee2** [comment]
@neojp A test is failing. I think there may be a broken internal link. Can you check what happened?

**Comment by neojp** [comment]
> @ijlee2: A test is failing. I think there may be a broken internal link. Can you check what happened?

Yes, I noticed that the tree view page is still being referenced. I've already added a task to make sure this is handled before I consider this is ready to be merged.

> - [ ] Remove Tree View page references

**Comment by locks** [comment]
Do you have time to update the PR?

**Comment by neojp** [comment]
@locks @ijlee2 I have updated and hopefully finished this PR. Let me know if you think we should have any more changes.

**Review by ijlee2 — APPROVED** [review]
@neojp Thank you very much for taking updated screenshots, highlighting areas of interest in each screenshot, and revising surrounding texts as needed.

I checked the Percy snapshots and reviewed the surrounding texts afterwards. I think your pull request is ready to be merged! 💯

**Pull request merged**
